# Generated by Django 3.2.4 on 2021-06-08 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('A7_app', '0002_auto_20210608_1223'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users_data',
            new_name='UsersData',
        ),
    ]
